import './globals.css'
import Navbar from './components/navbar'
import Footer from './components/footer'

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body className='font-sans' >
        <Navbar />
          {children}
        <Footer /> 
      </body>
    </html>
  )
}
